### ISSUE TITLE
error VGGFace fine-tune

### ISSUE THREAD

**Issue by carolinajimenez** [XiaoYee/emotion_classification#4]
When I ran the code, I got the error:

IndexError                                Traceback (most recent call last)
<ipython-input-13-c7bc734e5e35> in <module>()
      1 if __name__ == '__main__':
----> 2     main()

<ipython-input-12-2f3488b9f40b> in main()
      8 
      9         scheduler.step()
---> 10         train(epoch)
     11         val_accuracy = test()
     12 

<ipython-input-10-1c54a181a34c> in train(epoch)
     10 
     11         loss = loss_function(output, target)
---> 12         losses.update(loss.data[0], data.size(0))
     13 
     14         pred = output.data.max(1)[1]

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

I don't know why. Would you like to give me some advices? Thanks.

**Comment by noiran78** [comment]
Hi, I am experiencing the same problem. What is the workaround for you @cmgcar ?
